# -*- coding: utf-8 -*-
"""MEEN 683 Project-5B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ajpFzbw_yXdCYSeuWbiGPfU-mbn2VK5
"""

"""
Bi-Objective Optimization: Emissions vs. NPHR
Using Normal Boundary Intersection (NBI) Method

OBJECTIVES:
  J1 = Total Emissions (SO2, NOx, CO, CO2, Dust - weighted normalized sum)
  J2 = NPHR (Net Plant Heat Rate - efficiency in kcal/kWh)

METHOD:
  Normal Boundary Intersection (NBI)
  - Generates evenly-distributed Pareto points
  - Better coverage than weighted sum
  - Handles non-convex regions

ADDITIONAL OUTPUTS (reported but not optimized):
  - NTHR, HHV, Gross Load, Net Load
  - Individual emissions: SO2, NOx, CO, CO2, Dust
"""

import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive

# PROBLEM SETUP

# Bounds (physical units)
lb = np.array([65,  1,  0,  695000, 225, 815], dtype=float)
ub = np.array([95,  5,  4,  725000, 245, 855], dtype=float)

VAR_NAMES = [
    'x1: SH spray flow (t/h)',
    'x2: RH spray flow (t/h)',
    'x3: APH leakage (%)',
    'x4: Boiler energy (Mcal/h)',
    'x5: Feedwater temp (F)',
    'x6: Feedwater flow (t/h)',
]

def normalize(x):
    return (x - lb) / (ub - lb)

def unnormalize(x_norm):
    return lb + x_norm * (ub - lb)


# ALL REGRESSION MODELS

# Emissions
c_SO2  = np.array([0.078097, -0.022689,  0.055804, 0.0,  0.203204, 0.222676])
c_NOx  = np.array([0.019987, -0.222401,  0.116002, 0.0,  0.046811, 0.099485])
c_CO   = np.array([-0.130366, 0.557775, -0.448537, 0.0,  0.244969, 0.104185])
c_CO2  = np.array([9.657000, 10.239256,  6.363121, 6.4e-5, 39.745566, 50.958021])
c_Dust = np.array([-0.004186, -0.005248, -0.015129, 0.0,  0.003998, 0.004433])

AVG_SO2, AVG_NOx, AVG_CO, AVG_CO2, AVG_Dust = 437.50, 194.16, 260.93, 95367.0, 4.27
w_SO2, w_NOx, w_CO, w_CO2, w_Dust = 0.25, 0.25, 0.25, 0.15, 0.10

# Heat rates and efficiency
c_NPHR = np.array([0.2598, 0.3361, 0.2394, 0.001727, 1.1498, 1.4238])
c_NTHR = np.array([0.2379, 0.2909, 0.3460, 0.0000, 1.0487, 1.3266])  # g1
c_HHV  = np.array([0.3817, 0.3432, 0.2709, 0.0000, 1.7837, 2.2291])  # g2

# Power output
c_GrossLoad = np.array([0.0281, 0.0269, 0.0278, 0.0000, 0.1242, 0.1534])  # g3
c_NetLoad   = np.array([0.0282, 0.0101, 0.0246, 0.0000, 0.1141, 0.1447])  # g4

# OBJECTIVE FUNCTIONS

def J1_emissions(x):
    """Objective 1: Total weighted normalized emissions"""
    SO2_norm  = (c_SO2  @ x) / AVG_SO2
    NOx_norm  = (c_NOx  @ x) / AVG_NOx
    CO_norm   = (c_CO   @ x) / AVG_CO
    CO2_norm  = (c_CO2  @ x) / AVG_CO2
    Dust_norm = (c_Dust @ x) / AVG_Dust
    return w_SO2*SO2_norm + w_NOx*NOx_norm + w_CO*CO_norm + w_CO2*CO2_norm + w_Dust*Dust_norm

def J2_nphr(x):
    """Objective 2: Net Plant Heat Rate (lower is better)"""
    return c_NPHR @ x

def calc_all_outputs(x):
    """Calculate all outputs for a given design x"""
    return {
        'Emissions': J1_emissions(x),
        'NPHR': J2_nphr(x),
        'SO2': c_SO2 @ x,
        'NOx': c_NOx @ x,
        'CO': c_CO @ x,
        'CO2': c_CO2 @ x,
        'Dust': c_Dust @ x,
        'NTHR': c_NTHR @ x,
        'HHV': c_HHV @ x,
        'Gross_Load': c_GrossLoad @ x,
        'Net_Load': c_NetLoad @ x,
    }

# NORMAL BOUNDARY INTERSECTION (NBI) METHOD

def find_anchor_points():
    """Find individual optima (anchor points) for both objectives"""

    def solve_single_objective(objective_func):
        """Minimize a single objective"""
        bounds = [(0, 1) for _ in range(6)]
        x0_norm = 0.5 * np.ones(6)

        result = minimize(
            fun=lambda x: objective_func(unnormalize(x)),
            x0=x0_norm,
            method='SLSQP',
            bounds=bounds,
            options={'maxiter': 500, 'ftol': 1e-8, 'disp': False}
        )

        if result.success:
            return unnormalize(result.x)
        return None

    # Find anchor points
    x1_star = solve_single_objective(J1_emissions)  # Min emissions
    x2_star = solve_single_objective(J2_nphr)       # Min NPHR

    out1 = calc_all_outputs(x1_star)
    out2 = calc_all_outputs(x2_star)

    return x1_star, x2_star, out1, out2

def solve_nbi_subproblem(beta, anchor1_shifted, anchor2_shifted, J_utopia):
    """
    Solve single NBI subproblem for parameter beta ∈ [0,1]

    NBI formulation:
      Maximize: t  (distance along normal to CHIM)
      Subject to: J(x) = point_on_CHIM - t*normal

    Args:
        beta: Parameter in [0,1] defining point on CHIM
        anchor1_shifted: First anchor in shifted coordinates
        anchor2_shifted: Second anchor in shifted coordinates
        J_utopia: Utopia point for coordinate shift
    """

    # Point on CHIM (Convex Hull of Individual Minima)
    chim_point = beta * anchor1_shifted + (1 - beta) * anchor2_shifted

    # Normal vector to CHIM (perpendicular to line connecting anchors)
    chim_direction = anchor2_shifted - anchor1_shifted
    normal = np.array([-chim_direction[1], chim_direction[0]])
    normal = normal / np.linalg.norm(normal)  # Normalize

    # Optimization variables: [x1, x2, x3, x4, x5, x6, t]
    def objective_nbi(vars):
        """Minimize -t (equivalent to maximizing t)"""
        return -vars[6]

    def equality_constraint(vars):
        """Constraint: J(x) = chim_point - t*normal"""
        x_norm = vars[:6]
        t = vars[6]

        x_phys = unnormalize(x_norm)
        J1_val = J1_emissions(x_phys)
        J2_val = J2_nphr(x_phys)

        # Shift to utopia origin
        J_shifted = np.array([J1_val - J_utopia[0], J2_val - J_utopia[1]])

        # Should equal: chim_point - t*normal
        target = chim_point - t * normal

        return J_shifted - target  # Should be zero vector

    # Initial guess
    x0_norm = 0.5 * np.ones(6)
    t0 = 0.0
    vars0 = np.concatenate([x0_norm, [t0]])

    # Bounds
    bounds = [(0, 1) for _ in range(6)] + [(-10, 10)]  # x in [0,1], t unbounded

    # Solve
    result = minimize(
        fun=objective_nbi,
        x0=vars0,
        method='SLSQP',
        bounds=bounds,
        constraints={'type': 'eq', 'fun': equality_constraint},
        options={'maxiter': 1000, 'ftol': 1e-9, 'disp': False}
    )

    if result.success:
        x_opt = unnormalize(result.x[:6])
        t_opt = result.x[6]
        outputs = calc_all_outputs(x_opt)
        outputs['t'] = t_opt
        outputs['beta'] = beta
        outputs['x'] = x_opt
        return outputs

    return None


print("="*80)
print("BI-OBJECTIVE OPTIMIZATION: Emissions vs. NPHR")
print("Method: Normal Boundary Intersection (NBI)")
print("="*80)

#Find anchor points

print("\nStep 1: Finding anchor points (individual optima)...")

x1_star, x2_star, out1, out2 = find_anchor_points()

print(f"\nAnchor Point 1 (minimize Emissions):")
print(f"  Emissions: {out1['Emissions']:.6f}")
print(f"  NPHR:      {out1['NPHR']:.4f} kcal/kWh")
print(f"  NTHR:      {out1['NTHR']:.4f} kcal/kWh")
print(f"  Net Load:  {out1['Net_Load']:.4f} MW")

print(f"\nAnchor Point 2 (minimize NPHR):")
print(f"  Emissions: {out2['Emissions']:.6f}")
print(f"  NPHR:      {out2['NPHR']:.4f} kcal/kWh")
print(f"  NTHR:      {out2['NTHR']:.4f} kcal/kWh")
print(f"  Net Load:  {out2['Net_Load']:.4f} MW")

# Utopia point
J_utopia = np.array([out1['Emissions'], out2['NPHR']])
print(f"\nUtopia point (ideal but unattainable): [{J_utopia[0]:.6f}, {J_utopia[1]:.4f}]")

# Shift anchors to utopia origin
anchor1_shifted = np.array([0.0, out1['NPHR'] - J_utopia[1]])
anchor2_shifted = np.array([out2['Emissions'] - J_utopia[0], 0.0])

# Generate Pareto front(NBI)

print("\n" + "-"*80)
print("Step 2: Generating Pareto front using NBI...")
print("-"*80)

n_points = 41  # Number of Pareto points to generate
betas = np.linspace(0, 1, n_points)

results = []
for i, beta in enumerate(betas):
    outputs = solve_nbi_subproblem(beta, anchor1_shifted, anchor2_shifted, J_utopia)
    if outputs is not None:
        results.append(outputs)

    if (i+1) % 10 == 0:
        print(f"  Progress: {i+1}/{n_points} points computed...")

print(f"\n✓ Successfully generated {len(results)}/{n_points} Pareto points ({100*len(results)/n_points:.1f}% success)")

# Create DataFrame
df = pd.DataFrame(results)

# Summary


print("PARETO FRONT SUMMARY")
print(f"\nPrimary Objectives:")
print(f"  Emissions: {df['Emissions'].min():.6f} to {df['Emissions'].max():.6f}")
print(f"             Range: {df['Emissions'].max()-df['Emissions'].min():.6f} ({100*(df['Emissions'].max()-df['Emissions'].min())/df['Emissions'].min():.2f}%)")
print(f"  NPHR:      {df['NPHR'].min():.4f} to {df['NPHR'].max():.4f} kcal/kWh")
print(f"             Range: {df['NPHR'].max()-df['NPHR'].min():.4f} ({100*(df['NPHR'].max()-df['NPHR'].min())/df['NPHR'].min():.2f}%)")

print(f"\nAdditional Outputs:")
print(f"  NTHR:       {df['NTHR'].min():.4f} to {df['NTHR'].max():.4f} kcal/kWh")
print(f"  HHV:        {df['HHV'].min():.4f} to {df['HHV'].max():.4f} kcal/kg")
print(f"  Net Load:   {df['Net_Load'].min():.4f} to {df['Net_Load'].max():.4f} MW")
print(f"  Gross Load: {df['Gross_Load'].min():.4f} to {df['Gross_Load'].max():.4f} MW")

print(f"\nTradeoff Analysis:")
emit_change = 100*(df['Emissions'].max()-df['Emissions'].min())/df['Emissions'].min()
nphr_change = 100*(df['NPHR'].max()-df['NPHR'].min())/df['NPHR'].min()
print(f"  Reducing emissions by {emit_change:.2f}% → increases NPHR by {nphr_change:.2f}%")
print(f"  Improving efficiency (NPHR) by {nphr_change:.2f}% → increases emissions by {emit_change:.2f}%")

# VISUALIZATION



fig = plt.figure(figsize=(18, 10))
gs = fig.add_gridspec(3, 3, hspace=0.35, wspace=0.35)

fig.suptitle('NBI Method: Emissions vs NPHR Pareto Front\nWith Complete Regression Model Outputs',
             fontsize=14, fontweight='bold')

# Plot 1: Main Pareto Front (large)
ax1 = fig.add_subplot(gs[0:2, 0:2])

scatter = ax1.scatter(df['Emissions'], df['NPHR'], c=df['beta'], cmap='viridis',
                     s=120, alpha=0.8, edgecolor='black', linewidth=1.5, zorder=3)
ax1.plot(df['Emissions'], df['NPHR'], 'b--', alpha=0.4, linewidth=2, zorder=1)

# Anchor points
ax1.scatter([out1['Emissions']], [out1['NPHR']],
           c='red', s=500, marker='*', label='Min Emissions',
           zorder=10, edgecolor='darkred', linewidth=2)
ax1.scatter([out2['Emissions']], [out2['NPHR']],
           c='green', s=500, marker='*', label='Min NPHR',
           zorder=10, edgecolor='darkgreen', linewidth=2)

# Utopia point (unattainable)
ax1.scatter([J_utopia[0]], [J_utopia[1]],
           c='gold', s=500, marker='X', label='Utopia (ideal)',
           zorder=10, edgecolor='black', linewidth=2)

ax1.set_xlabel('J₁: Total Emissions (normalized, weighted)', fontweight='bold', fontsize=12)
ax1.set_ylabel('J₂: NPHR (kcal/kWh)', fontweight='bold', fontsize=12)
ax1.set_title(f'Pareto Front: {len(df)} Evenly-Distributed Points', fontweight='bold', fontsize=13)
ax1.legend(loc='best', fontsize=10)
ax1.grid(True, alpha=0.3)

cbar = plt.colorbar(scatter, ax=ax1)
cbar.set_label('β (NBI parameter)', fontsize=11, fontweight='bold')

# Add tradeoff annotation
ax1.annotate('Better\nEmissions', xy=(df['Emissions'].min(), df['NPHR'].mean()),
            xytext=(df['Emissions'].min()-0.001, df['NPHR'].mean()),
            fontsize=10, color='red', fontweight='bold', ha='right', va='center',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))

ax1.annotate('Better\nEfficiency', xy=(df['Emissions'].mean(), df['NPHR'].min()),
            xytext=(df['Emissions'].mean(), df['NPHR'].min()-5),
            fontsize=10, color='green', fontweight='bold', ha='center', va='top',
            bbox=dict(boxstyle='round', facecolor='white', alpha=0.7))

# Table 1: NTHR Values (replacing graph)
ax2 = fig.add_subplot(gs[0, 2])
ax2.axis('off')

# Select representative NTHR values
n_table_rows = 8
table_indices = np.linspace(0, len(df)-1, n_table_rows, dtype=int)

nthr_table_data = [['β', 'NTHR\n(kcal/kWh)']]
for i in table_indices:
    row = df.iloc[i]
    nthr_table_data.append([
        f"{row['beta']:.2f}",
        f"{row['NTHR']:.2f}"
    ])

nthr_table = ax2.table(cellText=nthr_table_data, cellLoc='center', loc='center',
                       bbox=[0, 0, 1, 1])
nthr_table.auto_set_font_size(False)
nthr_table.set_fontsize(9)
nthr_table.scale(1, 1.8)

# Header styling
for j in range(2):
    nthr_table[(0, j)].set_facecolor('#9C27B0')
    nthr_table[(0, j)].set_text_props(weight='bold', color='white')

ax2.text(0.5, 1.05, 'Net Turbine Heat Rate', ha='center', fontsize=11,
        fontweight='bold', transform=ax2.transAxes)

# Table 2: Net Load Values (replacing graph)
ax3 = fig.add_subplot(gs[1, 2])
ax3.axis('off')

# Select representative Net Load values
netload_table_data = [['β', 'Net Load\n(MW)']]
for i in table_indices:
    row = df.iloc[i]
    netload_table_data.append([
        f"{row['beta']:.2f}",
        f"{row['Net_Load']:.2f}"
    ])

netload_table = ax3.table(cellText=netload_table_data, cellLoc='center', loc='center',
                          bbox=[0, 0, 1, 1])
netload_table.auto_set_font_size(False)
netload_table.set_fontsize(9)
netload_table.scale(1, 1.8)

# Header styling
for j in range(2):
    netload_table[(0, j)].set_facecolor('#4CAF50')
    netload_table[(0, j)].set_text_props(weight='bold', color='white')

ax3.text(0.5, 1.05, 'Power Output', ha='center', fontsize=11,
        fontweight='bold', transform=ax3.transAxes)

# Plot 2: Individual emissions vs NPHR comparison
ax4 = fig.add_subplot(gs[2, 0:2])

# Normalize emissions and NPHR to [0,1] for comparison
emissions_norm = (df[['SO2', 'NOx', 'CO', 'Dust']] - df[['SO2', 'NOx', 'CO', 'Dust']].min()) / \
                 (df[['SO2', 'NOx', 'CO', 'Dust']].max() - df[['SO2', 'NOx', 'CO', 'Dust']].min())
nphr_norm = (df['NPHR'] - df['NPHR'].min()) / (df['NPHR'].max() - df['NPHR'].min())

# Plot emissions
ax4.plot(df['beta'], emissions_norm['SO2'], 'o-', label='SO₂', linewidth=2, markersize=5, alpha=0.8)
ax4.plot(df['beta'], emissions_norm['NOx'], 's-', label='NOₓ', linewidth=2, markersize=5, alpha=0.8)
ax4.plot(df['beta'], emissions_norm['CO'], '^-', label='CO', linewidth=2, markersize=5, alpha=0.8)
ax4.plot(df['beta'], emissions_norm['Dust'], 'v-', label='Dust', linewidth=2, markersize=5, alpha=0.8)

# Plot NPHR for comparison
ax4.plot(df['beta'], nphr_norm, 'D-', label='NPHR', linewidth=3, markersize=6,
        color='black', alpha=0.6, linestyle='--')

ax4.set_xlabel('β (NBI parameter)', fontweight='bold', fontsize=11)
ax4.set_ylabel('Normalized Value [0-1]', fontweight='bold', fontsize=11)
ax4.set_title('Emission Components vs NPHR Comparison (Normalized)', fontweight='bold', fontsize=11)
ax4.legend(fontsize=9, loc='best', ncol=3)
ax4.grid(True, alpha=0.3)
ax4.set_xlim(-0.05, 1.05)
ax4.set_ylim(-0.05, 1.05)

# Add annotation explaining normalization
ax4.text(0.02, 0.98, 'All values normalized to [0,1] for comparison',
        transform=ax4.transAxes, fontsize=8, va='top',
        bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.3))

# Table 3: Representative solutions table
ax5 = fig.add_subplot(gs[2, 2])
ax5.axis('off')

n_show = 6
indices = np.linspace(0, len(df)-1, n_show, dtype=int)

table_data = [['β', 'Emissions', 'NPHR', 'Net Load']]
for i in indices:
    row = df.iloc[i]
    table_data.append([
        f"{row['beta']:.2f}",
        f"{row['Emissions']:.4f}",
        f"{row['NPHR']:.1f}",
        f"{row['Net_Load']:.2f}"
    ])

table = ax5.table(cellText=table_data, cellLoc='center', loc='center',
                 bbox=[0, 0.05, 1, 0.9])
table.auto_set_font_size(False)
table.set_fontsize(8)
table.scale(1, 2)

for j in range(4):
    table[(0, j)].set_facecolor('#2196F3')
    table[(0, j)].set_text_props(weight='bold', color='white')

ax5.text(0.5, 0.97, 'Representative Solutions', ha='center', fontsize=10,
        fontweight='bold', transform=ax5.transAxes)

# DETAILED OUTPUT TABLE

print(f"PARETO-OPTIMAL SOLUTIONS (showing every {n_points//10}th point)\n\n")

display_cols = ['beta', 'Emissions', 'NPHR', 'NTHR', 'HHV', 'Net_Load', 'Gross_Load']
display_df = df[display_cols].iloc[::n_points//10]

print(display_df.to_string(index=False))

print("\nDone\n")
print(f"Generated {len(df)} evenly-distributed Pareto-optimal solutions")
print("All regression models included and tracked")
drive.mount('/content/drive')
plt.savefig('/content/drive/MyDrive/emissions_nphr_final.png', dpi=300, bbox_inches='tight')